routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\TagsController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/login', [LoginController::class, 'login'])->name('login');
Route::post('/signin', [LoginController::class, 'signin'])->name('signin');
Route::any('/logout', [LoginController::class, 'logout'])->name('logout');
Route::get('/register', [LoginController::class, 'register'])->name('register');
Route::post('/submit', [LoginController::class, 'submit'])->name('submit');

Route::get('/', [FrontendController::class, 'list'])->name('list');
Route::get('/view/{id}', [FrontendController::class, 'view'])->name('view');
Route::post('/comment/save/{article_id}', [FrontendController::class, 'store'])->name('comment.save');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::resource('category', CategoryController::class);
    Route::resource('tags', TagsController::class);
    Route::resource('articles', ArticleController::class);
});

resources/views/layouts/footer.blade.php
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <script>
                    document.write(new Date().getFullYear())
                </script> 
            </div>
        </div>
    </div>
</footer>

resources/views/layouts/head.blade.php
<head>

    <meta charset="utf-8" />
    <title>Admin & Dashboard Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
    <meta content="Themesbrand" name="author" />
    <!-- App favicon -->
    <link rel="shortcut icon" href={{ asset('assets/images/favicon.ico') }}>

    <!-- Layout config Js -->
    <script src={{asset('assets/js/layout.js')  }}></script>
    <!-- Bootstrap Css -->
    <link href={{ asset('assets/css/bootstrap.min.css') }} rel="stylesheet" type="text/css" />
    <!-- Icons Css -->
    <link href={{ asset('assets/css/icons.min.css') }} rel="stylesheet" type="text/css" />
    <!-- App Css-->
    <link href={{ asset('assets/css/app.min.css') }} rel="stylesheet" type="text/css" />
    <!-- custom Css-->
    <link href={{ asset('assets/css/custom.min.css') }} rel="stylesheet" type="text/css" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/remixicon/4.0.1/remixicon.css" integrity="sha512-ZH3KB6wI5ADHaLaez5ynrzxR6lAswuNfhlXdcdhxsvOUghvf02zU1dAsOC6JrBTWbkE1WNDNs5Dcfz493fDMhA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
</head>

resources/views/layouts/header.blade.php
        <header id="page-topbar">
            <div class="layout-width">
                <div class="navbar-header">
                    <div class="d-flex">
                        <!-- LOGO -->
                        <div class="navbar-brand-box horizontal-logo">
                            <a href="index.html" class="logo logo-dark">
                                <span class="logo-sm">
                                    <img src={{ asset('assets/images/logo-sm.png') }} alt="" height="22">
                                </span>
                                <span class="logo-lg">
                                    <img src={{ asset('assets/images/logo-dark.png') }} alt="" height="17">
                                </span>
                            </a>

                            <a href="index.html" class="logo logo-light">
                                <span class="logo-sm">
                                    <img src={{ asset('assets/images/logo-sm.png') }} alt="" height="22">
                                </span>
                                <span class="logo-lg">
                                    <img src={{ asset('assets/images/logo-light.png') }} alt="" height="17">
                                </span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </header>

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="en" data-layout="vertical" data-topbar="light" data-sidebar="dark" data-sidebar-size="lg"
    data-sidebar-image="none" data-preloader="disable">
@include('layouts.head')

<body>

    <!-- Begin page -->
    <div id="layout-wrapper">

        @include('layouts.header')
        @include('layouts.sidebar')
        <div class="vertical-overlay"></div>
        @yield('body')
        
    </div>
    <!-- END layout-wrapper -->



    <!--start back-to-top-->
    <button onclick="topFunction()" class="btn btn-danger btn-icon" id="back-to-top">
        <i class="ri-arrow-up-line"></i>
    </button>
    <!--end back-to-top-->

    <!--preloader-->
    <div id="preloader">
        <div id="status">
            <div class="spinner-border text-primary avatar-sm" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>
        </div>
    </div>

    <!-- Theme Settings -->

    @include('layouts.footer')
    @include('layouts.script')
</body>

</html>

resources/views/layouts/script.blade.php
    <!-- JAVASCRIPT -->
    <script src={{ asset('assets/libs/bootstrap/js/bootstrap.bundle.min.js') }}></script>
    <script src={{ asset('assets/libs/simplebar/simplebar.min.js') }}></script>
    <script src={{ asset('assets/libs/node-waves/waves.min.js') }}></script>
    <script src={{ asset('assets/libs/feather-icons/feather.min.js') }}></script>
    <script src={{ asset('assets/js/pages/plugins/lord-icon-2.1.0.js') }}></script>
    <script src={{ asset('assets/js/plugins.js') }}></script>

    <!--jquery cdn-->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <!-- apexcharts -->
    <script src={{ asset('assets/libs/apexcharts/apexcharts.min.js') }}></script>

    <!-- Dashboard init -->
    <script src={{ asset('assets/js/pages/dashboard-crm.init.js') }}></script>

    <!-- App js -->
    <script src={{ asset('assets/js/app.js') }}></script>

    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    <script src="{{ asset('assets/js/pages/select2.init.js') }}"></script>

resources/views/layouts/sidebar.blade.php
<div class="app-menu navbar-menu">
    <!-- LOGO -->
    <div class="navbar-brand-box">
        <!-- Dark Logo-->
        <button type="button" class="btn btn-sm p-0 fs-20 header-item float-end btn-vertical-sm-hover"
            id="vertical-hover">
            <i class="ri-record-circle-line"></i>
        </button>
    </div>

    <div id="scrollbar">
        <div class="container-fluid">

            <div id="two-column-menu">
            </div>
            <ul class="navbar-nav" id="navbar-nav">
                <li class="menu-title"><span data-key="t-menu">Menu</span></li>
                <li class="nav-item">
                    <a class="nav-link menu-link" href="{{ route('home') }}">
                        <i class="ri-dashboard-2-line"></i> <span data-key="t-dashboards">Dashboards</span>
                    </a>
                </li> 

                <li class="nav-item">
                    <a class="nav-link menu-link" href="{{ route('category.index')}}">
                        <i class="ri-honour-line"></i> <span data-key="t-category">Manage Category</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link menu-link" href="{{ route('tags.index')}}">
                        <i class="ri-honour-line"></i> <span data-key="t-category">Manage Tags</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link menu-link" href="{{ route('articles.index')}}">
                        <i class="ri-honour-line"></i> <span data-key="t-category">Manage Articles</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link menu-link" href="{{ route('logout') }}">
                        <i class="ri-honour-line"></i> <span data-key="t-logout">Logout</span>
                    </a>
                </li>

            </ul>
        </div>
        <!-- Sidebar -->
    </div>

    <div class="sidebar-background"></div>
</div>