routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\TagsController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/login', [LoginController::class, 'login'])->name('login');
Route::post('/signin', [LoginController::class, 'signin'])->name('signin');
Route::any('/logout', [LoginController::class, 'logout'])->name('logout');
Route::get('/register', [LoginController::class, 'register'])->name('register');
Route::post('/submit', [LoginController::class, 'submit'])->name('submit');

Route::get('/', [FrontendController::class, 'list'])->name('list');
Route::get('/view/{id}', [FrontendController::class, 'view'])->name('view');
Route::post('/comment/save/{article_id}', [FrontendController::class, 'store'])->name('comment.save');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::resource('category', CategoryController::class);
    Route::resource('tags', TagsController::class);
    Route::resource('articles', ArticleController::class);
});

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use HasFactory;

    protected $fillable = ['*'];
    
    public function comments()
    {
       return $this->hasmany(Comment::class, 'article_id', 'id');
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use App\Models\Category;
use App\Models\Tags;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $articles=Article::where('user_id', Auth::id())->get();
        return view('articles.index', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $categories = Category::get();
        $tags = Tags::get();
        return view('articles.create', compact('categories', 'tags'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'description' => 'required',
            'image' => 'required',
            'category' => 'required',
            'tag' => 'required'
        ]);

        if ($request->hasFile('image')) {
            $fileName = time() . '.' . $request->file('image')->getClientOriginalExtension();
            $request->file('image')->storeAs('public/articles', $fileName);
        } else {
            $fileName = '';
        }
        $article=new Article();
        $article->user_id = Auth::id();
        $article->title = $request->title;
        $article->cat_id = $request->category;
        $article->tag_ids = json_encode($request->tag);
        $article->description = $request->description;
        $article->image = $fileName;
        $article->save();
        return redirect()->route('articles.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $categories = Category::get();
        $tags = Tags::get();
        $article = Article::find($id);
        return view('articles.edit', compact('categories', 'tags', 'article'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $this->validate($request, [
            'title' => 'required',
            'description' => 'required',
            'category' => 'required',
            'tag' => 'required'
        ]);

        $article = Article::find($id);

        if ($request->hasFile('image')) {
            $fileName = time() . '.' . $request->file('image')->getClientOriginalExtension();
            $request->file('image')->storeAs('public/articles', $fileName);
        } else {
            $fileName = $article->image;
        }

        $article->title = $request->title;
        $article->cat_id = $request->category;
        $article->tag_ids = json_encode($request->tag);
        $article->description = $request->description;
        $article->image = $fileName;
        $article->save();
        return redirect()->route('articles.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $article=Article::find($id);
        $article->delete();
        return redirect()->route('articles.index');
    }
}

resources/views/articles/create.blade.php
@extends('layouts.master')
@section('body')
    <div class="main-content">
        <div class="page-content">
            <div class="container-fluid">
                <div class="col-12">
                    <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                        <h4 class="mb-sm-0">Create Article</h4>
                    </div>
                </div>
            </div>
            <!-- end page title -->

            <div class="row">
                <div class="col-xxl-12">
                    <div class="card">
                        <div class="card-header align-items-center d-flex">
                            <h4 class="card-title mb-0 flex-grow-1">Create Article</h4>
                        </div><!-- end card header -->

                        <div class="card-body">
                            <div class="live-preview">
                                <form method="POST" action="{{ route('articles.store') }}" enctype="multipart/form-data">
                                    @csrf
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="mb-3">
                                                <label for="Nameinput" class="form-label"> Title</label>
                                                <input type="text" class="form-control" placeholder="Enter Title"
                                                    id="Nameinput" name="title">
                                            </div>
                                            @error('title')
                                                <span class="text-danger">{{ $message }}</span>
                                            @enderror
                                        </div>

                                        <div class="col-md-6">
                                            <div class="mb-3">
                                                <label for="Nameinput" class="form-label">Select catgeoy</label>
                                                <select class="form-control" name="category">
                                                    <option value="">--select--</option>
                                                    @foreach ($categories as $cat)
                                                        <option value="{{ $cat->id }}"> {{ $cat->name }}
                                                        </option>
                                                    @endforeach
                                                </select>
                                            </div>
                                            @error('category')
                                                <span class="text-danger">{{ $message }}</span>
                                            @enderror
                                        </div>

                                        <div class="col-lg-6">
                                            <h6 class="fw-semibold">Select Tags</h6>
                                            <select class="js-example-basic-multiple" name="tag[]" multiple="multiple">
                                                <option value="" disabled>--select--</option>
                                                @foreach ($tags as $tag)
                                                    <option value="{{ $tag->id }}"> {{ $tag->name }}
                                                    </option>
                                                @endforeach
                                            </select>
                                            @error('tag')
                                                <span class="text-danger">{{ $message }}</span>
                                            @enderror
                                        </div>

                                        <div class="col-md-6">
                                            <div class="mb-3">
                                                <label for="Nameinput" class="form-label"> Description</label>
                                                <textarea class="form-control" rows="5" placeholder="Enter description" name="description"></textarea>
                                            </div>
                                            @error('description')
                                                <span class="text-danger">{{ $message }}</span>
                                            @enderror
                                        </div>

                                        <div class="col-md-6">
                                            <div class="mb-3">
                                                <label for="Nameinput" class="form-label"> Image</label>
                                                <input type="file" class="form-control" name="image">
                                            </div>
                                            @error('image')
                                                <span class="text-danger">{{ $message }}</span>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-lg-12">
                                            <div class="text-end">
                                                <button type="submit" class="btn btn-primary">Submit</button>
                                            </div>
                                        </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> <!-- container-fluid -->
    </div>
    <!-- End Page-content -->
    </div>
    @include('layouts.footer')
@endsection

resources/views/articles/edit.blade.php
@extends('layouts.master')
@section('body')
    <div class="main-content">

        <div class="page-content">
            <div class="container-fluid">

                <!-- start page title -->
                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                            <h4 class="mb-sm-0">Edit Article</h4>
                        </div>
                    </div>
                </div>
                <!-- end page title -->

                <div class="row">
                    <div class="col-xxl-12">
                        <div class="card">
                            <div class="card-header align-items-center d-flex">
                                <h4 class="card-title mb-0 flex-grow-1">Edit Article</h4>
                            </div><!-- end card header -->

                            <div class="card-body">
                                <div class="live-preview">
                                    <form method="POST" action="{{ route('articles.update', $article->id) }}"
                                        enctype="multipart/form-data">
                                        @csrf
                                        @method('PATCH')
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="mb-3">
                                                    <label for="Nameinput" class="form-label"> Title</label>
                                                    <input type="text" class="form-control" placeholder="Enter Title"
                                                        value="{{ $article->title }}" name="title">
                                                </div>
                                                @error('title')
                                                    <span class="text-danger">{{ $message }}</span>
                                                @enderror
                                            </div>

                                            <div class="col-md-6">
                                                <div class="mb-3">
                                                    <label for="Nameinput" class="form-label">Select catgeoy</label>
                                                    <select class="form-control" name="category">
                                                        <option value="">--select--</option>
                                                        @foreach ($categories as $cat)
                                                            <option value="{{ $cat->id }}"> {{ $cat->name }}
                                                            </option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                                @error('category')
                                                    <span class="text-danger">{{ $message }}</span>
                                                @enderror
                                            </div>

                                            <div class="col-md-6">
                                                <div class="mb-3">
                                                    <label for="Nameinput" class="form-label">Select Tags <small> (press
                                                            Ctrl to select multiple tags)</small></label>
                                                    <select class="form-control" name="tag[]" multiple>
                                                        @foreach ($tags as $tag)
                                                            <option value="{{ $tag->id }}"> {{ $tag->name }}
                                                            </option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                                @error('tag')
                                                    <span class="text-danger">{{ $message }}</span>
                                                @enderror
                                            </div>

                                            <div class="col-md-6">
                                                <div class="mb-3">
                                                    <label for="Nameinput" class="form-label"> Description</label>
                                                    <textarea class="form-control" rows="5" placeholder="Enter description" name="description">
                                                        {{  $article->description }}
                                                    </textarea>
                                                </div>
                                                @error('description')
                                                    <span class="text-danger">{{ $message }}</span>
                                                @enderror
                                            </div>

                                            <div class="col-md-6">
                                                <div class="mb-3">
                                                    <label for="Nameinput" class="form-label"> Image</label>
                                                    <input type="file" class="form-control" name="image">
                                                </div>
                                                @error('image')
                                                    <span class="text-danger">{{ $message }}</span>
                                                @enderror
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="text-end">
                                                    <button type="submit" class="btn btn-primary">Submit</button>
                                                </div>
                                            </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> <!-- container-fluid -->
        </div>
        <!-- End Page-content -->
    </div>
    @include('layouts.footer')
@endsection

resources/views/articles/index.blade.php
@extends('layouts.master')
@section('body')
    <div class="main-content">

        <div class="page-content">
            <div class="container-fluid">

                <!-- start page title -->
                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                            <h4 class="mb-sm-0">List Artcles</h4>
                        </div>
                        <a href="{{ route('articles.create') }}" class="btn btn-info add-btn"><i
                                class="ri-add-fill me-1 align-bottom"></i>Create Article</a>
                    </div>
                </div>
                <!-- end page title -->
                <div class="row pt-3">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <h5 class="card-title mb-0">List Artcles</h5>
                            </div>
                            <div class="card-body">
                                <table id="example"
                                    class="table table-bordered dt-responsive nowrap table-striped align-middle"
                                    style="width:100%">
                                    <thead>
                                        <tr>
                                            <th data-ordering="false">SR No.</th>
                                            <th data-ordering="false">Name</th>
                                            <th data-ordering="false">Catgeory</th>
                                            <th data-ordering="false">Tags</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($articles as $article)
                                        @php
                                            $category = App\Models\Category::where('id', $article->cat_id)->first();
                                        @endphp
                                            <tr>
                                                <td>{{ $loop->index + 1 }}</td>
                                                <td>{{ $article->title }}</td>
                                                <td>{{ $category->name }}</td>
                                                <td>
                                                    @php
                                                         foreach( json_decode($article->tag_ids)  as $a_tag) {
                                                            $tag = App\Models\tags::where('id', $a_tag)->first();
                                                            echo '->' . $tag->name . '<br>';
                                                         }
                                                    @endphp
                                                   
                                                </td>
                                                <td>
                                                    <div class="dropdown d-inline-block">
                                                        <button class="btn btn-soft-secondary btn-sm dropdown"
                                                            type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                                            <i class="ri-more-fill align-middle"></i>
                                                        </button>
                                                        <ul class="dropdown-menu dropdown-menu-end">
                                                            <li><a href="{{ route('articles.edit', $article->id) }}"
                                                                    class="dropdown-item"><i
                                                                        class="ri-eye-fill align-bottom me-2 text-muted"></i>
                                                                    Edit</a></li>
                                                            <li>
                                                                <form method="POST" action="{{ route('articles.destroy',$article->id) }}">
                                                                    @csrf
                                                                    @method('DELETE')
                                                                    <button type="submit" class="dropdown-item remove-item-btn">
                                                                        <i
                                                                            class="ri-delete-bin-fill align-bottom me-2 text-muted"></i>
                                                                        Delete
                                                                    </button>
                                                                </form>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div><!--end col-->
                </div><!--end row-->
            </div>
            <!-- container-fluid -->
        </div>
        <!-- End Page-content -->
    </div>
    @include('layouts.footer')
@endsection